name: Screenshot Website

on: push

jobs:
  screenshot:
    name: Screenshot
    runs-on: ubuntu-latest
    steps:
    - name: Screenshot Website
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://gu3.me/
        destination: screenshot.png
        width: 1920
        height: 1080
    - name: Download screenshot
      uses: actions/download-artifact@v2
      with:
        name: screenshot
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: repo
    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: "screenshot.png"
        target: "repo/screenshot.png"
    - name: Commit files
      run: |
        cd repo
        git config --local user.email "12881812+xezno@users.noreply.github.com"
        git config --local user.name "Alex"
        git add .
        git commit -m "Add website screenshot" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        directory: "repo"
        github_token: ${{ secrets.GITHUB_TOKEN }}
